export type RaidSlotStatus = "AVAILABLE" | "ACTIVE" | "RESULT_HELD" | "CONFIRMED" | "DISCARDED" | "EXPIRED";
export type RaidAttemptStatus = "RUNNING" | "RESULT_HELD" | "DISCARDED" | "CONFIRMED";
export type RaidAttemptMode = "REWARD" | "PRACTICE";
export type RaidReward = { cosmeticTickets: number; gemBoxes: number; rice: number };
export type RaidCombatEvent = { sequence: number; logicalTick: number; type: string; actor: "PLAYER" | "BOSS" | null; target: "PLAYER" | "BOSS" | null; damage: number | null; critical: boolean | null; hpBefore: number | null; hpAfter: number | null; escalationStage: number | null; bossAttack: number | null; bossDefense: number | null };
export type RaidAttemptResult = { damage: number; grade: string; sealContribution: number; endedAt: string | null; playerDied: boolean; timeLimitReached: boolean; reward: RaidReward | null };
export type RaidAttempt = { attemptId: string; sessionId: string; slotOrdinal: number; mode: RaidAttemptMode; status: RaidAttemptStatus; inputSnapshot: { contentVersion: string; rewardVersion: string; seed: number; player: { level: number; maxHp: number; attack: number; defense: number; defensePenetration: number; skillIds: string[]; skillLoadout: string[]; mainGemPreset: string; cosmeticEffectIds: string[] }; boss: { bossId: string; displayName: string; contentVersion: string; initialAttack: number; initialDefense: number; maxTicks: number; tickDurationMilliseconds: number; escalationIntervalTicks: number; escalationBasisPoints: number }; capturedAt: string }; tickDurationMilliseconds: number; durationMilliseconds: number; startedAt: string; completableAt: string; endedAt: string | null; currentResult: RaidAttemptResult; terminalResult: RaidAttemptResult | null; renderingTimeline: { tickDurationMilliseconds: number; durationMilliseconds: number; events: RaidCombatEvent[] } };
export type RaidState = { featureAvailable: boolean; unlockStageId: string; unlocked: boolean; session: { sessionId: string; contentVersion: string; rewardVersion: string; settlesAt: string; status: "OPEN" | "SETTLING" | "SETTLED_SUCCESS" | "SETTLED_FAILURE"; sealTarget: number; sealedContribution: number; sealProgressBasisPoints: number; sealSuccessScheduled: boolean; serverNow: string }; slots: { ordinal: number; status: RaidSlotStatus; attemptsStarted: number; attemptsRemaining: number; currentAttemptId: string | null; resultHeld: boolean }[]; currentAttempt: RaidAttempt | null; ranking: { sessionId: string; settled: boolean; currentRank: number | null; currentSealContribution: number; topEntries: { rank: number; nickname: string; sealContribution: number }[]; nextCursor: string | null; totalEligibleAccounts: number }; claims: { items: { claimId: string; sessionId: string; kind: string; status: string; reward: RaidReward; createdAt: string; claimedAt: string | null }[]; claimableCount: number; claimedCount: number; nextCursor: string | null } };
export class RaidApiError extends Error { constructor(public readonly code: string, public readonly retryable = false) { super(code); } }
type Envelope<T> = { data: T };
type Command<T> = { commandId: string; idempotencyKey: string; status: string; result: T };
function command<T>(path: string, key: string, body: unknown = {}): Promise<T> { return request<Command<T>>(path, { method: "POST", headers: { "Content-Type": "application/json", "Idempotency-Key": key }, body: JSON.stringify(body) }).then(({ result }) => result); }
export const raidApi = { state: () => request<RaidState>(""), start: (mode: RaidAttemptMode, key: string = crypto.randomUUID()) => command<RaidAttempt>("/attempts", key, { mode }), retry: (attemptId: string, key: string = crypto.randomUUID()) => command<RaidAttempt>(`/attempts/${encodeURIComponent(attemptId)}/retry`, key), confirm: (attemptId: string, key: string = crypto.randomUUID()) => command<RaidState>(`/attempts/${encodeURIComponent(attemptId)}/confirm`, key), discard: (attemptId: string, key: string = crypto.randomUUID()) => command<RaidState>(`/attempts/${encodeURIComponent(attemptId)}/discard`, key), claim: (claimId: string, key: string = crypto.randomUUID()) => command<{ claim: RaidState["claims"]["items"][number]; state: RaidState["claims"] }>(`/claims/${encodeURIComponent(claimId)}`, key) };
async function request<T>(path: string, init?: RequestInit): Promise<T> { const response = await fetch(`/api/v1/raid${path}`, { credentials: "include", headers: { Accept: "application/json", ...init?.headers }, ...init }); const body = await response.json().catch(() => ({})) as Envelope<T> & { code?: string; retryable?: boolean; messageKey?: string }; if (!response.ok) throw new RaidApiError(body.code ?? body.messageKey ?? `HTTP_${response.status}`, body.retryable === true); return body.data; }
