import { useEffect, useRef, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { RaidApiError, raidApi, type RaidState } from "./api";
import { RaidBattle } from "./RaidBattle";
import "./raid.css";

function clock(ms: number) { const seconds = Math.max(0, Math.ceil(ms / 1000)); return `${String(Math.floor(seconds / 3600)).padStart(2, "0")}:${String(Math.floor(seconds % 3600 / 60)).padStart(2, "0")}:${String(seconds % 60).padStart(2, "0")}`; }
function slotLabel(status: string) { return ({ AVAILABLE: "대기", ACTIVE: "전투 중", RESULT_HELD: "결과 보관", CONFIRMED: "확정됨", DISCARDED: "포기", EXPIRED: "종료" } as Record<string, string>)[status] ?? status; }
function rewardLabel(reward: { cosmeticTickets: number; gemBoxes: number; rice: number }) { return `티켓 ${reward.cosmeticTickets} · 보석함 ${reward.gemBoxes} · 쌀 ${reward.rice.toLocaleString()}`; }
export function RaidScreen({ now = Date.now }: { now?: () => number }) {
  const client = useQueryClient(); const [clockNow, setClockNow] = useState(now()); const uncertain = useRef<{ label: string; retry: () => void } | undefined>(undefined);
  const state = useQuery({ queryKey: ["raid"], queryFn: raidApi.state, retry: false, refetchInterval: 5_000 });
  useEffect(() => { const timer = window.setInterval(() => setClockNow(now()), 1_000); return () => window.clearInterval(timer); }, [now]);
  const refresh = () => Promise.all([["raid"], ["inventory"], ["auth", "session"], ["character-stats"], ["battle"]].map((queryKey) => client.invalidateQueries({ queryKey })));
  const mutation = useMutation({ mutationFn: ({ fn, retry }: { fn: () => Promise<unknown>; retry: () => void }) => fn(), onSuccess: () => { uncertain.current = undefined; void refresh(); }, onError: (error, variables) => { if (!(error instanceof RaidApiError) || !error.code.startsWith("RAID_")) uncertain.current = { label: "명령", retry: variables.retry }; void refresh(); } });
  const execute = (label: string, action: (key: string) => Promise<unknown>) => { const key = crypto.randomUUID(); const retry = () => mutation.mutate({ fn: () => action(key), retry }); mutation.mutate({ fn: () => action(key), retry }); };
  if (state.isLoading) return <section className="raid-screen"><div className="domain-message">레이드 정보를 불러오는 중입니다.</div></section>;
  if (state.error) { const auth = state.error instanceof RaidApiError && state.error.code === "AUTHENTICATION_REQUIRED"; return <section className="raid-screen"><div className="domain-message error" role="alert"><strong>{auth ? "로그인이 필요합니다." : "레이드 콘텐츠를 불러오지 못했습니다."}</strong><button type="button" onClick={() => state.refetch()}>다시 시도</button></div></section>; }
  const data = state.data as RaidState;
  const allTerminal = data.slots.length > 0 && data.slots.every((slot) => ["CONFIRMED", "DISCARDED", "EXPIRED"].includes(slot.status));
  const currentRewardSlotOrdinal = data.slots.reduce<number | undefined>((current, slot) => slot.status === "AVAILABLE" && (current === undefined || slot.ordinal < current) ? slot.ordinal : current, undefined);
  if (data.currentAttempt) {
    const activeSlot = data.slots.find((slot) => slot.ordinal === data.currentAttempt?.slotOrdinal);
    return <RaidBattle attempt={data.currentAttempt} attemptsStarted={activeSlot?.attemptsStarted} now={now} busy={mutation.isPending} uncertainCommand={uncertain.current} onRetry={() => execute("다시 도전", (key) => raidApi.retry(data.currentAttempt!.attemptId, key))} onConfirm={() => execute("결과 확정", (key) => raidApi.confirm(data.currentAttempt!.attemptId, key))} onDiscard={() => execute("나가기", (key) => raidApi.discard(data.currentAttempt!.attemptId, key))} />;
  }
  return <section className="raid-screen" aria-labelledby="raid-title"><header className="raid-header"><div><p>DAILY · SEAL RAID</p><h2 id="raid-title">오늘의 봉인</h2><span>{data.session.status === "OPEN" ? (data.session.sealSuccessScheduled ? "봉인 성공 예정" : "봉인 진행 중") : data.session.status}</span></div><div><small>정산까지</small><strong>{clock(Date.parse(data.session.settlesAt) - clockNow)}</strong></div></header><section className="raid-seal"><strong>{data.session.sealedContribution.toLocaleString()} / {data.session.sealTarget.toLocaleString()}</strong><div role="progressbar" aria-label="공동 봉인 진행도" aria-valuemin={0} aria-valuemax={10000} aria-valuenow={data.session.sealProgressBasisPoints}><i style={{ width: `${data.session.sealProgressBasisPoints / 100}%` }} /></div></section><section className="raid-slots" aria-label="오늘의 도전 슬롯">{data.slots.map((slot) => <article key={slot.ordinal}><h3>{slot.ordinal}번 슬롯 · {slotLabel(slot.status)}</h3><p>시작 {slot.attemptsStarted}회 · 남음 {slot.attemptsRemaining}회</p>{slot.ordinal === currentRewardSlotOrdinal && <button type="button" disabled={mutation.isPending} onClick={() => execute("보상 도전", (key) => raidApi.start("REWARD", key))}>보상 도전</button>}</article>)}{allTerminal && <article className="raid-practice"><h3>보상 슬롯을 모두 사용했습니다.</h3><p>보상 없이 전투 기록을 확인할 수 있습니다.</p><button type="button" disabled={mutation.isPending} onClick={() => execute("연습 전투", (key) => raidApi.start("PRACTICE", key))}>연습 전투</button></article>}</section><section className="raid-columns"><article><h3>TOP 100</h3><ol>{data.ranking.topEntries.map((entry) => <li key={`${entry.rank}-${entry.nickname}`}><strong>{entry.rank}위</strong><span>{entry.nickname}</span><em>{entry.sealContribution.toLocaleString()}</em></li>)}</ol><p>{data.ranking.currentRank === null ? "순위 집계 전" : `내 순위 ${data.ranking.currentRank}위`}</p>{data.ranking.currentRank !== null && data.ranking.currentRank > 100 && <p>TOP 100 밖 · 내 기여 {data.ranking.currentSealContribution.toLocaleString()}</p>}</article><article><h3>미수령 보상</h3>{data.claims.items.length === 0 ? <p>받을 보상이 없습니다.</p> : data.claims.items.map((claim) => <div className="raid-claim" key={claim.claimId}><span>{claim.kind === "DAILY_RANK" ? "일일 순위 보상" : "개인 보상"}</span><p>{rewardLabel(claim.reward)}</p>{claim.status === "CLAIMABLE" ? <button type="button" disabled={mutation.isPending} onClick={() => execute("보상 받기", (key) => raidApi.claim(claim.claimId, key))}>보상 받기</button> : <small>수령 완료</small>}</div>)}</article></section></section>;
}
