# Generated by Django 5.2.14 on 2026-06-24 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('closet', '0005_parent_style_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SnapClothingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('clothing_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='closet.clothingitem')),
            ],
            options={
                'db_table': 'snap_clothing_items',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SnapPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True)),
                ('photos', models.JSONField(default=list)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('seasons', models.JSONField(blank=True, default=list)),
                ('styles', models.JSONField(blank=True, default=list)),
                ('tpos', models.JSONField(blank=True, default=list)),
                ('height', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('weight', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('skin_tone', models.CharField(blank=True, max_length=30)),
                ('is_hidden', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clothing_items', models.ManyToManyField(blank=True, related_name='snap_posts', through='snaps.SnapClothingItem', to='closet.clothingitem')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snap_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'snap_posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SnapComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snap_comments', to=settings.AUTH_USER_MODEL)),
                ('snap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='snaps.snappost')),
            ],
            options={
                'db_table': 'snap_comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='snapclothingitem',
            name='snap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snaps.snappost'),
        ),
        migrations.CreateModel(
            name='SnapFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_snap_users', to=settings.AUTH_USER_MODEL)),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snap_followers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'snap_follows',
                'unique_together': {('follower', 'following')},
            },
        ),
        migrations.CreateModel(
            name='SnapLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snap_likes', to=settings.AUTH_USER_MODEL)),
                ('snap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='snaps.snappost')),
            ],
            options={
                'db_table': 'snap_likes',
                'unique_together': {('snap', 'user')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='snapclothingitem',
            unique_together={('snap', 'clothing_item')},
        ),
        migrations.CreateModel(
            name='SnapScrap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('snap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scraps', to='snaps.snappost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snap_scraps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'snap_scraps',
                'unique_together': {('snap', 'user')},
            },
        ),
    ]
