# Generated by Django 5.2.14 on 2026-06-24 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snaps', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SnapHidden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('snap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hidden_by', to='snaps.snappost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hidden_snaps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'snap_hidden',
                'unique_together': {('snap', 'user')},
            },
        ),
        migrations.CreateModel(
            name='SnapReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('snap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='snaps.snappost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snap_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'snap_reports',
                'unique_together': {('snap', 'user')},
            },
        ),
    ]
