# Generated by Django 5.2.14 on 2026-06-24 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfits', '0004_integer_star_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendationevent',
            name='was_worn',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
