import { useCallback, useEffect, useState } from "react";
import { AdminKafkaOps, AdminMarketAnomaly, createApiClient } from "@hanjjak/client-sdk";
import { adminErrorMessage } from "./presentation";
import "./styles.css";

const api = createApiClient().admin;
export function KafkaView() {
  const [data, setData] = useState<AdminKafkaOps | null>(null);
  const [anomalies, setAnomalies] = useState<AdminMarketAnomaly[]>([]);
  const [error, setError] = useState<string | null>(null);
  const load = useCallback(() => { Promise.all([api.kafkaOps(), api.marketAnomalies()]).then(([ops, alerts]) => { setData(ops); setAnomalies(alerts); }).catch((failure) => setError(adminErrorMessage(failure))); }, []);
  useEffect(load, [load]);
  if (error) return <div className="content"><div className="alert error">{error}</div><button className="secondary" onClick={load}>다시 시도</button></div>;
  if (!data) return <div className="content"><div className="state"><div className="loader" /><p>Kafka 상태를 불러오는 중입니다.</p></div></div>;
  const totalFailures = data.outboxFailed + data.consumers.reduce((sum, item) => sum + item.failures, 0);
  return <div className="content kafka-ops"><section className="overview-head"><div><p>거래 이벤트가 Kafka를 통해 얼마나 빠르고 안전하게 처리됐는지 확인합니다.</p><span>숫자가 높을수록 처리된 이벤트가 많다는 뜻입니다.</span></div><button className="secondary" onClick={load}>↻ 새로고침</button></section><section className="health-banner"><div className={totalFailures || anomalies.length ? "health-icon danger" : "health-icon"}>{totalFailures || anomalies.length ? "!" : "✓"}</div><div><span>KAFKA PIPELINE</span><strong>{totalFailures || anomalies.length ? "확인이 필요한 이벤트가 있습니다" : "Kafka 처리 정상"}</strong><small>Outbox → Kafka → Consumer</small></div><b>{totalFailures || anomalies.length ? `${number(totalFailures + anomalies.length)}건 확인` : "정상"}</b></section><section className="metric-grid"><Metric label="전달 요청" value={data.outboxClaimed} tone="blue" /><Metric label="전달 성공" value={data.outboxSent} tone="mint" /><Metric label="재시도" value={data.outboxRetry} tone="amber" /><Metric label="최종 실패" value={data.outboxFailed} tone="red" /></section><article className="panel table-panel"><header className="panel-title"><h2>이상 거래 알림</h2><p>평균 가격보다 2배 이상 높은 거래를 자동 표시합니다.</p></header>{anomalies.length === 0 ? <div className="empty"><p>현재 이상 거래가 없습니다.</p></div> : <div className="table-wrap"><table><thead><tr><th>아이템</th><th>거래 가격</th><th>기준 가격</th><th>배율</th><th>발생 시각</th></tr></thead><tbody>{anomalies.map((alert) => <tr key={alert.alertId}><td><strong>{alert.itemId}</strong></td><td>{number(alert.unitPrice)}쌀</td><td>{alert.referencePrice.toFixed(2)}쌀</td><td><span className="badge danger">{alert.deviationRatio.toFixed(2)}배</span></td><td>{new Date(alert.occurredAt).toLocaleString("ko-KR")}</td></tr>)}</tbody></table></div>}</article><article className="panel table-panel"><header className="panel-title"><h2>Consumer별 처리 현황</h2><p>중복·실패·처리량을 한눈에 확인합니다.</p></header>{data.consumers.length === 0 ? <div className="empty"><p>아직 Consumer 처리 기록이 없습니다.</p></div> : <div className="table-wrap"><table><thead><tr><th>Consumer</th><th>처리 이벤트</th><th>중복</th><th>실패</th><th>배치 수</th><th>평균 배치</th><th>처리 시간</th></tr></thead><tbody>{data.consumers.map((consumer) => <tr key={consumer.name}><td><strong>{consumer.name}</strong></td><td>{number(consumer.events)}</td><td><span className={consumer.duplicates ? "badge pending" : "badge success"}>{number(consumer.duplicates)}</span></td><td><span className={consumer.failures ? "badge danger" : "badge success"}>{number(consumer.failures)}</span></td><td>{number(consumer.batches)}</td><td>{consumer.averageBatchSize.toFixed(1)}건</td><td>{consumer.processingSeconds.toFixed(2)}초</td></tr>)}</tbody></table></div>}</article></div>;
}
function Metric({ label, value, tone }: { label: string; value: number; tone: string }) { return <article className={`metric ${tone}`}><span>{label}</span><strong>{number(value)}</strong></article>; }
function number(value: number) { return value.toLocaleString("ko-KR"); }
